### ISSUE TITLE
Users unable to post in forum

### ISSUE THREAD

**Issue by yellowled** [s9y/theme_board#4] opened 2022-07-16 10:42 UTC
I'm pretty sure this is not an issue with the s9y board theme but with a (recent?) update of phpBB. (Last recent post seems to be from 2022-06-10, so it was probably working then?)

```html
<div id="message-box" class="message-box">
    <textareaname="message" id="message" rows="15" cols="76" tabindex="4" onselect="storeCaret(this);" onclick="storeCaret(this);" onkeyup="storeCaret(this);" onfocus="initInsertions();" class="inputbox" style="position: relative;"></textareaname="message">
</div>
```
The missing space between `textarea` and `name` makes browsers no longer “recognize” it as a textarea, which is why it's not styled etc. Basically, users are not able to post.

**Comment by mariohommel** [comment] 2022-07-16 11:05
So far as I can see there was no update of phpBB done the last couple of weeks.

**Comment by yellowled** [comment] 2022-07-16 13:55
That was just my assumption after realizing that there are *no* template files in the theme_board respository. Something™ must have changed between June and now, an update to phpBB seemed like an option.

**Comment by onli** [comment] 2022-07-17 12:05
According to https://github.com/s9y/dev/blob/master/infrastructure/infrastructure.md I don't have access to the board's server, and I think that's correct. I am also not aware of having changed anything. Maybe uberspace updated the PHP version or made an emergency update of phpBB?

Likely requires someone to dive into the board's code and see what the problem is.

**Comment by yellowled** [comment] 2022-07-17 12:37
Yeah, sorry. My assignment was based on the assumption that this was related to the board theme, which I don't think it is. (Someone™ got in contact via email with me about this.)

**Comment by mariohommel** [comment] 2022-07-17 12:44
I'll copy the forum to a local machine and update phpBB to the latest version. If this helps we can do it in production, too.

**Comment by th-h** [comment] 2022-07-17 15:17
@mariohommel is THE MAN for the forums. :) Reassigning.

**Comment by mariohommel** [comment] 2022-07-17 21:00
I updated the phpBB to the latest release. This solved the problem so users can post to the forum again.

**Closed as completed by mariohommel** 2022-07-17 21:00 UTC
Labels: bug
